name: recallapp
description: English vocabulary enricher
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # fonts
  google_fonts: ^5.1.0

  # bloc
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # http
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1

  # json
  json_annotation: ^4.8.1

  # api key
  envied: ^0.3.0+3

  # storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # text-to-speech
  flutter_tts: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  envied_generator: ^0.3.0+3

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
